{
 "title": "DLH User Details",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "user",
    "label": "User",
    "query": "SELECT DISTINCT `user` FROM `trino-logs-experiment`.mv_query_metrics;"
   }
  ]
 },
 "panels": [
  {
   "title": "Queries success rate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    toStartOfInterval(create_time, INTERVAL 1 hour) AS time,\r\n    count() AS value\r\nFROM `trino-logs-experiment`.mv_query_metrics\r\nWHERE create_time BETWEEN toDateTime($__fromTime) AND toDateTime($__toTime)\r\n  AND `user` = '${user}'\r\n  AND query_state = 'FINISHED'\r\nGROUP BY time\r\nORDER BY time"
    },
    {
     "rawSql": "SELECT \r\n    toStartOfInterval(create_time, INTERVAL 1 hour) AS time,\r\n    count() AS value\r\nFROM `trino-logs-experiment`.mv_query_metrics\r\nWHERE create_time BETWEEN toDateTime($__fromTime) AND toDateTime($__toTime)\r\n  AND `user` = '${user}'\r\n  AND query_state = 'FAILED'\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Request types success rate",
   "type": "table",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    query_type,\r\n    count() AS query_count,\r\n    avg(wall_time) AS avg_wall_time,\r\n    max(wall_time) AS max_wall_time,\r\n    sum(physical_input_bytes) AS total_input_bytes,\r\n    sum(output_bytes) AS total_output_bytes\r\nFROM `trino-logs-experiment`.mv_query_metrics\r\nWHERE create_time BETWEEN toDateTime($__fromTime) AND toDateTime($__toTime)\r\n  AND `user` = '${user}'\r\nGROUP BY query_type\r\nORDER BY query_type DESC"
    }
   ]
  },
  {
   "title": "User query performance",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    toStartOfInterval(create_time, INTERVAL 1 hour) AS time_bucket,\r\n    avg(wall_time) AS avg_wall_time,\r\n    max(wall_time) AS max_wall_time,\r\n    avg(cpu_time) AS avg_cpu_time,\r\n    max(cpu_time) AS max_cpu_time,\r\n    avg(queued_time) AS avg_queue_time,\r\n    avg(execution_time) AS avg_execution_time\r\nFROM `trino-logs-experiment`.mv_query_metrics\r\nWHERE create_time BETWEEN toDateTime($__fromTime) AND toDateTime($__toTime)\r\n  AND `user` = '${user}'\r\nGROUP BY time_bucket\r\nORDER BY time_bucket"
    }
   ]
  },
  {
   "title": "Memory usage stats",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    toStartOfInterval(create_time, INTERVAL 1 hour) AS time_bucket,\r\n    avg(peak_user_memory_bytes) AS avg_memory_bytes,\r\n    max(peak_user_memory_bytes) AS max_memory_bytes,\r\n    avg(peak_task_total_memory) AS avg_task_memory,\r\n    max(peak_task_total_memory) AS max_task_memory\r\nFROM `trino-logs-experiment`.mv_query_metrics\r\nWHERE create_time BETWEEN toDateTime($__fromTime) AND toDateTime($__toTime)\r\n  AND `user` = '${user}'\r\nGROUP BY time_bucket\r\nORDER BY time_bucket"
    }
   ]
  },
  {
   "title": "TOP-25 Target tables",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    target_catalog,\r\n    target_schema,\r\n    target_table,\r\n    count() AS query_count,\r\n    avg(wall_time) AS avg_wall_time,\r\n    avg(cpu_time) AS avg_cpu_time,\r\n    sum(physical_input_bytes) AS total_input_bytes,\r\n    sum(physical_input_rows) AS total_input_rows\r\nFROM `trino-logs-experiment`.mv_query_metrics\r\nWHERE create_time BETWEEN toDateTime($__fromTime) AND toDateTime($__toTime)\r\n  AND `user` = '${user}'\r\n  AND target_catalog != ''\r\nGROUP BY target_catalog, target_schema, target_table\r\nORDER BY query_count DESC\r\nLIMIT 25"
    }
   ]
  },
  {
   "title": "TOP-25 Source tables by read bytes",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 56 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    source_catalog,\r\n    source_schema,\r\n    source_table,\r\n    count() AS queries_count,\r\n    sum(source_physical_input_bytes) AS total_read_bytes,\r\n    sum(source_physical_input_rows) AS total_read_rows\r\nFROM `trino-logs-experiment`.mv_source_tables\r\nWHERE event_time >= $__fromTime AND event_time <= $__toTime AND `user` = '${user}'\r\nGROUP BY source_catalog, source_schema, source_table\r\nORDER BY total_read_bytes DESC\r\nLIMIT 25;"
    }
   ]
  },
  {
   "title": "TOP-100 Longest queries",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 56 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    query_id,\r\n    toDateTime(create_time) AS start_time,\r\n    wall_time,\r\n    query_type,\r\n    physical_input_bytes,\r\n    output_bytes,\r\n    peak_user_memory_bytes,\r\n    cumulative_memory\r\nFROM `trino-logs-experiment`.mv_query_metrics\r\nWHERE create_time BETWEEN toDateTime($__fromTime) AND toDateTime($__toTime)\r\n  AND `user` = '${user}'\r\nORDER BY wall_time DESC\r\nLIMIT 100\r\n"
    }
   ]
  }
 ]
}