{
 "title": "DLH Query Details",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "query_id", "label": "Query ID" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Query State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  query_state\r\nFROM\r\n  `trino-logs-experiment`.mv_query_metrics\r\nWHERE\r\n  query_id = '${query_id}'"
    }
   ]
  },
  {
   "title": "Parallelism metrics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    peak_task_user_memory / peak_user_memory_bytes AS parallelism_ratio,\r\n    peak_task_total_memory AS peak_task_memory,\r\n    peak_user_memory_bytes AS peak_memory,\r\n    cpu_time / wall_time AS cpu_efficiency\r\nFROM\r\n    `trino-logs-experiment`.mv_query_metrics\r\nWHERE\r\n    query_id = '${query_id}'\r\n"
    }
   ]
  },
  { "title": "Main Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Session Stats",
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n\t`user`,\r\n\tuser_agent,\r\n\t`source`,\r\n\tenvironment,\r\n\tquery_type\r\nFROM\r\n\t`trino-logs-experiment`.mv_query_metrics\r\nWHERE\r\n\tquery_id = '${query_id}'"
    }
   ]
  },
  {
   "title": "SQL Query",
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 17, "w": 16, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n\treplaceRegexpAll(\r\n    replaceAll(\r\n        replaceAll(\r\n            JSONExtractString(l.logs, 'eventPayload', 'metadata', 'query'), \r\n            '\\\\\\\\n', \r\n            '\\n'\r\n        ),\r\n        '\\\\\"', \r\n        '\"'\r\n    ),\r\n    '(SELECT|FROM|WHERE|GROUP BY|ORDER BY|HAVING|JOIN|ON)',\r\n    '\\n\\\\1'\r\n) AS formatted_query\r\nFROM\r\n\t`trino-logs`.logs l\r\nWHERE\r\n\tquery_id = '${query_id}';"
    }
   ]
  },
  {
   "title": "Time Stats",
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tcreate_time,\r\n\texecution_start_time,\r\n\tend_time,\r\n\twall_time,\r\n\tqueued_time,\r\n\tanalysis_time,\r\n\tplanning_time,\r\n\texecution_time\r\nFROM\r\n\t`trino-logs-experiment`.mv_query_metrics\r\nWHERE\r\n\tquery_id = '${query_id}'"
    }
   ]
  },
  {
   "title": "Bytes I/O",
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tpeak_user_memory_bytes,\r\n\tpeak_task_user_memory,\r\n\tpeak_task_total_memory,\r\n\tphysical_input_bytes,\r\n\tprocessed_input_bytes,\r\n\tinternal_network_bytes,\r\n\ttotal_bytes,\r\n\toutput_bytes,\r\n\twritten_bytes,\r\n\tcumulative_memory::UInt64 AS cumulative_memory\r\nFROM\r\n\t`trino-logs-experiment`.mv_query_metrics\r\nWHERE\r\n\tquery_id = '${query_id}'"
    }
   ]
  },
  {
   "title": "Query Plan",
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 20, "w": 16, "x": 8, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tJSONExtractString(l.logs, 'eventPayload', 'metadata', 'plan') AS formatted_query\r\nFROM\r\n\t`trino-logs`.logs l\r\nWHERE\r\n\tquery_id = '${query_id}';"
    }
   ]
  },
  {
   "title": "Rows I/O",
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tphysical_input_rows,\r\n\tprocessed_input_rows,\r\n\tinternal_network_rows,\r\n\toutput_rows,\r\n\twritten_rows,\r\n\ttotal_rows\r\nFROM\r\n\t`trino-logs-experiment`.mv_query_metrics\r\nWHERE\r\n\tquery_id = '${query_id}'"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Source Tables",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    source_catalog,\r\n    source_schema,\r\n    source_table,\r\n    source_physical_input_bytes,\r\n    source_physical_input_rows\r\nFROM\r\n    `trino-logs-experiment`.mv_source_tables\r\nWHERE\r\n    query_id = '${query_id}'\r\nORDER BY\r\n    source_physical_input_bytes DESC\r\n"
    }
   ]
  },
  {
   "title": "Target Tables",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    target_catalog,\r\n    target_schema,\r\n    target_table,\r\n    written_bytes,\r\n    written_rows\r\nFROM\r\n    `trino-logs-experiment`.mv_query_metrics\r\nWHERE\r\n    query_id = '${query_id}'\r\nORDER BY\r\n    written_bytes DESC\r\n"
    }
   ]
  },
  {
   "title": "Previous Queries",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    end_time AS time,\r\n    wall_time AS wall_time,\r\n    execution_time AS execution_time,\r\n    query_id\r\nFROM\r\n    `trino-logs-experiment`.mv_query_metrics\r\nWHERE\r\n    `user` = (\r\n        SELECT `user`\r\n        FROM `trino-logs-experiment`.mv_query_metrics\r\n        WHERE query_id = '${query_id}'\r\n        LIMIT 1\r\n    )\r\n    AND `source` = (\r\n        SELECT `source`\r\n        FROM `trino-logs-experiment`.mv_query_metrics\r\n        WHERE query_id = '${query_id}'\r\n        LIMIT 1\r\n    )\r\n    AND query_type = (\r\n        SELECT query_type\r\n        FROM `trino-logs-experiment`.mv_query_metrics\r\n        WHERE query_id = '${query_id}'\r\n        LIMIT 1\r\n    )\r\n    AND query_state = 'FINISHED'\r\nORDER BY\r\n    end_time DESC\r\nLIMIT 100\r\n"
    }
   ]
  },
  {
   "title": "Time per phase",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    'Analysis' AS phase,\r\n    analysis_time AS duration\r\nFROM\r\n    `trino-logs-experiment`.mv_query_metrics\r\nWHERE\r\n    query_id = '${query_id}'\r\n\r\nUNION ALL\r\n\r\nSELECT\r\n    'Planning' AS phase,\r\n    planning_time AS duration\r\nFROM\r\n    `trino-logs-experiment`.mv_query_metrics\r\nWHERE\r\n    query_id = '${query_id}'\r\n\r\nUNION ALL\r\n\r\nSELECT\r\n    'Queued' AS phase,\r\n    queued_time AS duration\r\nFROM\r\n    `trino-logs-experiment`.mv_query_metrics\r\nWHERE\r\n    query_id = '${query_id}'\r\n\r\nUNION ALL\r\n\r\nSELECT\r\n    'Execution' AS phase,\r\n    execution_time AS duration\r\nFROM\r\n    `trino-logs-experiment`.mv_query_metrics\r\nWHERE\r\n    query_id = '${query_id}'\r\n\r\nORDER BY\r\n    duration DESC\r\n"
    }
   ]
  },
  {
   "title": "Error Message",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    failure_type,\r\n    failure_message,\r\n    failures_json,\r\n    time_create_time\r\nFROM\r\n    `trino-logs-experiment`.mv_query_errors\r\nWHERE\r\n    query_id = '${query_id}'\r\n"
    }
   ]
  }
 ]
}