{
 "title": "DLH Data Storage Details",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "catalog",
    "label": "Catalog",
    "query": "SELECT DISTINCT\n    catalog\nFROM `trino-logs-experiment`.v_unique_table_references\nORDER BY catalog;"
   },
   {
    "name": "schema",
    "label": "Schema",
    "query": "SELECT DISTINCT\n    schema\nFROM `trino-logs-experiment`.v_unique_table_references\nWHERE catalog = '$catalog'\nORDER BY schema;"
   },
   {
    "name": "table",
    "label": "Table",
    "query": "SELECT DISTINCT\n    table\nFROM `trino-logs-experiment`.v_unique_table_references\nWHERE catalog = '$catalog' AND schema = '$schema'\nORDER BY table;\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Time Stats",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    toStartOfInterval(s.event_time, INTERVAL 1 hour) AS time,\r\n    avg(q.wall_time) AS avg_wall_time,\r\n    avg(q.cpu_time) AS avg_cpu_time,\r\n    avg(q.execution_time) AS avg_execution_time,\r\n    avg(q.physical_input_read_time) AS avg_read_time\r\nFROM `trino-logs-experiment`.mv_source_tables s\r\nJOIN `trino-logs-experiment`.mv_query_metrics q ON s.query_id = q.query_id\r\nWHERE \r\n    s.event_time BETWEEN toDateTime($__fromTime) AND toDateTime($__toTime)\r\n    AND s.source_catalog = '${catalog}'\r\n    AND s.source_schema = '${schema}'\r\n    AND s.source_table IN(${table})\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Queue Stats",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    toStartOfInterval(s.event_time, INTERVAL 1 hour) AS time,\r\n    avg(q.queued_time) AS avg_queued_time,\r\n    max(q.queued_time) AS max_queued_time,\r\n    avg(q.analysis_time + q.planning_time) AS avg_planning_time\r\nFROM `trino-logs-experiment`.mv_source_tables s\r\nJOIN `trino-logs-experiment`.mv_query_metrics q ON s.query_id = q.query_id\r\nWHERE \r\n    s.event_time BETWEEN toDateTime($__fromTime) AND toDateTime($__toTime)\r\n    AND s.source_catalog = '${catalog}'\r\n    AND s.source_schema = '${schema}'\r\n    AND s.source_table IN(${table})\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Bytes/Rows Stats",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    toStartOfInterval(event_time, INTERVAL 1 hour) AS time,\r\n    sum(source_physical_input_bytes) AS total_bytes_read,\r\n    sum(source_physical_input_rows) AS total_rows_read,\r\n    avg(source_physical_input_bytes) AS avg_bytes_per_query,\r\n    avg(source_physical_input_rows) AS avg_rows_per_query,\r\n    max(source_physical_input_bytes) AS max_bytes_per_query,\r\n    max(source_physical_input_rows) AS max_rows_per_query\r\nFROM `trino-logs-experiment`.mv_source_tables\r\nWHERE \r\n    event_time BETWEEN toDateTime($__fromTime) AND toDateTime($__toTime)\r\n    AND source_catalog = '${catalog}'\r\n    AND source_schema = '${schema}'\r\n    AND source_table IN(${table})\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "TOP-10 Query Sources",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    q.source AS query_source,\r\n    q.user_agent,\r\n    count() AS query_count,\r\n    sum(s.source_physical_input_bytes) AS total_bytes_read,\r\n    avg(q.wall_time) AS avg_wall_time\r\nFROM `trino-logs-experiment`.mv_source_tables s\r\nJOIN `trino-logs-experiment`.mv_query_metrics q ON s.query_id = q.query_id\r\nWHERE \r\n    s.event_time BETWEEN toDateTime($__fromTime) AND toDateTime($__toTime)\r\n    AND s.source_catalog = '${catalog}'\r\n    AND s.source_schema = '${schema}'\r\n    AND s.source_table IN(${table})\r\nGROUP BY query_source, q.user_agent\r\nORDER BY query_count DESC\r\nLIMIT 10\r\n"
    }
   ]
  },
  {
   "title": "Query State Stats",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    q.query_state,\r\n    count() AS query_count,\r\n    avg(q.wall_time) AS avg_wall_time,\r\n    max(q.wall_time) AS max_wall_time\r\nFROM `trino-logs-experiment`.mv_source_tables s\r\nJOIN `trino-logs-experiment`.mv_query_metrics q ON s.query_id = q.query_id\r\nWHERE \r\n    s.event_time BETWEEN toDateTime($__fromTime) AND toDateTime($__toTime)\r\n    AND s.source_catalog = '${catalog}'\r\n    AND s.source_schema = '${schema}'\r\n    AND s.source_table IN(${table})\r\nGROUP BY q.query_state\r\nORDER BY q.query_state DESC"
    }
   ]
  },
  {
   "title": "Resources distribution by query type",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    q.query_type,\r\n    count() AS query_count,\r\n    avg(s.source_physical_input_bytes) AS avg_bytes_read,\r\n    avg(s.source_physical_input_rows) AS avg_rows_read,\r\n    avg(q.wall_time) AS avg_wall_time\r\nFROM `trino-logs-experiment`.mv_source_tables s\r\nJOIN `trino-logs-experiment`.mv_query_metrics q ON s.query_id = q.query_id\r\nWHERE \r\n    s.event_time BETWEEN toDateTime($__fromTime) AND toDateTime($__toTime)\r\n    AND s.source_catalog = '${catalog}'\r\n    AND s.source_schema = '${schema}'\r\n    AND s.source_table IN(${table})\r\nGROUP BY q.query_type\r\nORDER BY q.query_type DESC"
    }
   ]
  },
  {
   "title": "TOP-25 Queries by CPU Time",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    s.query_id,\r\n    q.user AS username,\r\n    q.query_type,\r\n    q.query_state,\r\n    s.source_physical_input_bytes AS bytes_read,\r\n    s.source_physical_input_rows AS rows_read,\r\n    q.cpu_time AS cpu_time,\r\n    q.wall_time AS wall_time,\r\n    q.peak_user_memory_bytes AS peak_memory,\r\n    s.event_time\r\nFROM `trino-logs-experiment`.mv_source_tables s\r\nJOIN `trino-logs-experiment`.mv_query_metrics q ON s.query_id = q.query_id\r\nWHERE \r\n    s.event_time BETWEEN toDateTime($__fromTime) AND toDateTime($__toTime)\r\n    AND s.source_catalog = '${catalog}'\r\n    AND s.source_schema = '${schema}'\r\n    AND s.source_table IN(${table})\r\nORDER BY cpu_time DESC\r\nLIMIT 25"
    }
   ]
  },
  {
   "title": "TOP-25 Readers",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "rawSql": "-- Запрос для определения пользователей, которые чаще всего обращаются к таблице\r\nSELECT \r\n    q.user AS username,\r\n    count() AS query_count,\r\n    sum(s.source_physical_input_bytes) AS total_bytes_read,\r\n    sum(s.source_physical_input_rows) AS total_rows_read,\r\n    avg(q.cpu_time) AS avg_cpu_time,\r\n    avg(q.wall_time) AS avg_wall_time\r\nFROM `trino-logs-experiment`.mv_source_tables s\r\nJOIN `trino-logs-experiment`.mv_query_metrics q ON s.query_id = q.query_id\r\nWHERE \r\n    s.event_time BETWEEN toDateTime($__fromTime) AND toDateTime($__toTime)\r\n    AND s.source_catalog = '${catalog}'\r\n    AND s.source_schema = '${schema}'\r\n    AND s.source_table IN(${table})\r\nGROUP BY username\r\nORDER BY total_bytes_read DESC\r\nLIMIT 25\r\n"
    }
   ]
  }
 ]
}