{
 "title": "DLH Overview",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": "SELECT DISTINCT environment\nFROM `trino-logs-experiment`.mv_query_metrics"
   }
  ]
 },
 "panels": [
  {
   "title": "Data I/O comparison",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH daily_stats AS (\r\n    SELECT \r\n        toStartOfDay(q.execution_start_time) AS time,\r\n        sum(q.physical_input_bytes) AS bytes_read,\r\n        sum(q.written_bytes) AS bytes_written,\r\n        count(CASE WHEN q.physical_input_bytes > 0 THEN 1 END) AS read_queries,\r\n        count(CASE WHEN q.written_bytes > 0 THEN 1 END) AS write_queries,\r\n        count() AS total_queries\r\n    FROM `trino-logs-experiment`.mv_query_metrics q\r\n    WHERE \r\n        q.execution_start_time BETWEEN toDateTime($__fromTime) AND toDateTime($__toTime)\r\n        AND q.environment IN (${env})\r\n    GROUP BY time\r\n)\r\nSELECT\r\n    time,\r\n    bytes_read,\r\n    bytes_written,\r\n    read_queries,\r\n    write_queries,\r\n    total_queries,\r\n    (bytes_read / (bytes_read + bytes_written + 1)) * 100 AS read_percentage,\r\n    (bytes_written / (bytes_read + bytes_written + 1)) * 100 AS write_percentage,\r\n    (read_queries / (total_queries + 0.001)) * 100 AS read_query_percentage,\r\n    (write_queries / (total_queries + 0.001)) * 100 AS write_query_percentage\r\nFROM daily_stats\r\nORDER BY time\r\n"
    }
   ]
  },
  {
   "title": "Data I/O over time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    toStartOfDay(q.execution_start_time) AS time,\r\n    sum(q.physical_input_bytes) AS bytes_read,\r\n    sum(q.written_bytes) AS bytes_written,\r\n    sum(q.physical_input_rows) AS rows_read,\r\n    sum(q.written_rows) AS rows_written,\r\n    count(CASE WHEN q.physical_input_bytes > 0 THEN 1 END) AS read_queries,\r\n    count(CASE WHEN q.written_bytes > 0 THEN 1 END) AS write_queries\r\nFROM `trino-logs-experiment`.mv_query_metrics q\r\nWHERE \r\n    q.execution_start_time BETWEEN toDateTime($__fromTime) AND toDateTime($__toTime)\r\n    AND q.environment IN (${env})\r\nGROUP BY time\r\nORDER BY time\r\n"
    }
   ]
  },
  {
   "title": "Queries success rate",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    toStartOfDay(q.execution_start_time) AS time,\r\n    q.query_state,\r\n    count() AS query_count\r\nFROM `trino-logs-experiment`.mv_query_metrics q\r\nWHERE \r\n    q.execution_start_time BETWEEN toDateTime($__fromTime) AND toDateTime($__toTime)\r\n    AND q.query_state != ''\r\n    AND q.environment IN (${env})\r\nGROUP BY time, q.query_state\r\nORDER BY time, query_count DESC\r\n"
    }
   ]
  },
  {
   "title": "Data usage over time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    toStartOfDay(event_time) AS time,\r\n    sum(source_physical_input_bytes) AS total_bytes_read,\r\n    sum(source_physical_input_rows) AS total_rows_read,\r\n    avg(source_physical_input_bytes) AS avg_bytes_per_query\r\nFROM `trino-logs-experiment`.mv_source_tables s\r\n    INNER JOIN `trino-logs-experiment`.mv_query_metrics q\r\n    ON s.query_id = q.query_id AND q.environment IN (${env})\r\nWHERE event_time BETWEEN toDateTime($__fromTime) AND toDateTime($__toTime)\r\nGROUP BY time\r\nORDER BY time\r\n"
    }
   ]
  },
  {
   "title": "Memory usage over time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    toStartOfDay(q.execution_start_time) AS time,\r\n    avg(q.peak_user_memory_bytes) AS avg_peak_memory,\r\n    avg(q.physical_input_bytes) AS avg_input_bytes\r\nFROM `trino-logs-experiment`.mv_query_metrics q\r\nWHERE \r\n    q.execution_start_time BETWEEN toDateTime($__fromTime) AND toDateTime($__toTime)\r\n    AND q.environment IN (${env})\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Queue Stats",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    toStartOfDay(q.execution_start_time) AS time,\r\n    avg(q.queued_time) AS avg_queued_time,\r\n    max(q.queued_time) AS max_queued_time,\r\n    quantile(0.95)(q.queued_time) AS p95_queued_time,\r\n    avg(q.analysis_time + q.planning_time) AS avg_planning_time\r\nFROM `trino-logs-experiment`.mv_query_metrics q\r\nWHERE \r\n    q.execution_start_time BETWEEN toDateTime($__fromTime) AND toDateTime($__toTime)\r\n    AND q.environment IN (${env})\r\nGROUP BY time\r\nORDER BY time\r\n"
    }
   ]
  },
  {
   "title": "Time usage stats",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    toStartOfDay(q.execution_start_time) AS time,\r\n    avg(q.wall_time) AS avg_wall_time,\r\n    avg(q.cpu_time) AS avg_cpu_time,\r\n    avg(q.execution_time) AS avg_execution_time,\r\n    max(q.wall_time) AS max_wall_time,\r\n    quantile(0.95)(q.wall_time) AS p95_wall_time\r\nFROM `trino-logs-experiment`.mv_query_metrics q\r\nWHERE \r\n    q.execution_start_time BETWEEN toDateTime($__fromTime) AND toDateTime($__toTime)\r\n    AND q.wall_time > 0\r\n    AND q.environment IN (${env})\r\nGROUP BY time\r\nORDER BY time\r\n"
    }
   ]
  },
  {
   "title": "Query distribution per source",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    q.source AS query_source,\r\n    q.user_agent,\r\n    count() AS query_count,\r\n    sum(q.physical_input_bytes) AS total_bytes_read,\r\n    avg(q.wall_time) AS avg_wall_time\r\nFROM `trino-logs-experiment`.mv_query_metrics q\r\nWHERE \r\n    q.execution_start_time BETWEEN toDateTime($__fromTime) AND toDateTime($__toTime)\r\n    AND q.source != ''\r\n    AND q.environment IN (${env})\r\nGROUP BY query_source, q.user_agent\r\nORDER BY query_count DESC\r\nLIMIT 15\r\n"
    }
   ]
  },
  {
   "title": "TOP-25 Queries by bytes read",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    q.query_id,\r\n    q.user AS username,\r\n    q.query_type,\r\n    q.query_state,\r\n    q.physical_input_bytes AS bytes_read,\r\n    q.physical_input_rows AS rows_read,\r\n    q.wall_time AS wall_time,\r\n    q.cpu_time AS cpu_time,\r\n    q.peak_user_memory_bytes AS peak_memory,\r\n    q.execution_start_time\r\nFROM `trino-logs-experiment`.mv_query_metrics q\r\nWHERE \r\n    q.execution_start_time BETWEEN toDateTime($__fromTime) AND toDateTime($__toTime)\r\n    AND q.environment IN (${env})\r\nORDER BY bytes_read DESC\r\nLIMIT 25"
    }
   ]
  },
  {
   "title": "TOP-25 Users by queries",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    q.user AS username,\r\n    count() AS query_count,\r\n    sum(q.physical_input_bytes) AS total_bytes_read,\r\n    sum(q.physical_input_rows) AS total_rows_read,\r\n    avg(cpu_time) AS avg_cpu_time,\r\n    max(cpu_time) AS max_cpu_time,\r\n    sum(cpu_time) AS sum_cpu_time,\r\n    avg(q.wall_time) AS avg_wall_time,\r\n    max(q.wall_time) AS max_wall_time\r\nFROM `trino-logs-experiment`.mv_query_metrics q\r\nWHERE \r\n    q.execution_start_time BETWEEN toDateTime($__fromTime) AND toDateTime($__toTime)\r\n    AND q.user != ''\r\n    AND q.environment IN (${env})\r\nGROUP BY username\r\nORDER BY query_count DESC\r\nLIMIT 25\r\n"
    }
   ]
  },
  {
   "title": "TOP-25 Users by CPUTime",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    q.user AS username,\r\n    count() AS query_count,\r\n    sum(q.physical_input_bytes) AS total_bytes_read,\r\n    sum(q.physical_input_rows) AS total_rows_read,\r\n    avg(cpu_time) AS avg_cpu_time,\r\n    max(cpu_time) AS max_cpu_time,\r\n    sum(cpu_time) AS sum_cpu_time,\r\n    avg(q.wall_time) AS avg_wall_time,\r\n    max(q.wall_time) AS max_wall_time\r\nFROM `trino-logs-experiment`.mv_query_metrics q\r\nWHERE \r\n    q.execution_start_time BETWEEN toDateTime($__fromTime) AND toDateTime($__toTime)\r\n    AND q.user != ''\r\n    AND q.environment IN (${env})\r\nGROUP BY username\r\nORDER BY sum(cpu_time) DESC\r\nLIMIT 25\r\n"
    }
   ]
  },
  {
   "title": "TOP-25 Tables by bytes written",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    target_catalog AS catalog,\r\n    target_schema AS schema,\r\n    target_table AS table,\r\n    count() AS write_query_count,\r\n    sum(written_bytes) AS total_bytes_written,\r\n    sum(written_rows) AS total_rows_written,\r\n    max(written_bytes) AS max_bytes_per_query,\r\n    avg(written_bytes) AS avg_bytes_per_query,\r\n    avg(cpu_time) AS avg_cpu_time,\r\n    sum(cpu_time) AS sum_cpu_time,\r\n    max(wall_time) AS max_write_time,\r\n    avg(wall_time) AS avg_write_time\r\nFROM `trino-logs-experiment`.mv_query_metrics\r\nWHERE \r\n    execution_start_time BETWEEN toDateTime($__fromTime) AND toDateTime($__toTime)\r\n    AND target_catalog != ''\r\n    AND target_schema != ''\r\n    AND target_table != ''\r\n    AND written_bytes > 0\r\n    AND q.environment IN (${env})\r\nGROUP BY catalog, schema, table\r\nORDER BY total_bytes_written DESC\r\nLIMIT 25\r\n"
    }
   ]
  },
  {
   "title": "TOP-25 Tables by bytes read",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    s.source_catalog AS catalog,\r\n    s.source_schema AS schema,\r\n    s.source_table AS table,\r\n    count() AS read_query_count,\r\n    sum(s.source_physical_input_bytes) AS total_bytes_read,\r\n    sum(s.source_physical_input_rows) AS total_rows_read,\r\n    max(s.source_physical_input_bytes) AS max_bytes_per_query,\r\n    avg(s.source_physical_input_bytes) AS avg_bytes_per_query,\r\n    avg(q.wall_time) AS avg_read_time,\r\n    max(q.wall_time) AS max_read_time,\r\n    avg(q.cpu_time) AS avg_cpu_time,\r\n    sum(q.cpu_time) AS sum_cpu_time\r\nFROM `trino-logs-experiment`.mv_source_tables s\r\nJOIN `trino-logs-experiment`.mv_query_metrics q ON s.query_id = q.query_id\r\nWHERE \r\n    s.event_time BETWEEN toDateTime($__fromTime) AND toDateTime($__toTime)\r\n    AND s.source_catalog != ''\r\n    AND s.source_schema != ''\r\n    AND s.source_table != ''\r\n    AND s.source_physical_input_bytes > 0\r\n    AND q.environment IN (${env})\r\nGROUP BY catalog, schema, table\r\nORDER BY total_bytes_read DESC\r\nLIMIT 25\r\n"
    }
   ]
  }
 ]
}